services:
  redsoci-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - '8080:4000'
    depends_on:
      - db
    command: npm start
    container_name: redsoci-api
    profiles:
      - deployment

  redsoci-api-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - '8080:4000'
    depends_on:
      - db
    command: npm test
    container_name: redsoci-api-test
    profiles:
      - test
  redsoci-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - '8080:4000'
    depends_on:
      - db
    command: npm run dev
    container_name: redsoci-api-dev
    profiles:
      - dev
  db:
    container_name: db
    image: postgres
    restart: always
    command: -p 3200
    environment: 
      POSTGRES_DB: "redSocial"
      POSTGRES_PASSWORD: "TEST_SERVER"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3200:3200